### PR TITLE
Refactoring of operations

### PR DESCRIPTION
**Pull request by jsnoble**

### CODE REVIEW

**Comment by kstaken** [comment]
I believe asset.json is in the wrong place. Looking at Peter's PR for the kafka asset he has it in the root of `asset/` like normal.

**Comment by kstaken** [comment]
Also it shouldn't have version 1.0.0 since this is still in development.

**Comment by kstaken** [comment]
I was going to try to play with this but it occurs to me it's probably not actually usable since I don't know how to load the rules. Definitely need to get it usable outside the asset context so we can run some standalone experiments.

**Comment by kstaken** [comment]
refs #1

**Comment by kstaken** [comment]
How do you use this? Is it assuming the rules exist in the same asset bundle?

**Comment by kstaken** [comment]
As far as I can tell it does assume the rules are in the same asset bundle which is useless. We had discussed that rules need to come from a different asset bundle. Am I just misunderstanding how to use this?

**Comment by jsnoble** [comment]
I changed the schema to better reflect where rules live.
```
// example opConfig
{
           _op: 'transform',
            rules_file: 'transformRules1.txt',
            asset_name: some-asset-name-where-rules-live,
            selector_config: { _created: 'date' }
}
```

**Review by kstaken — APPROVED** [review]
Merging

**Pull request merged**
